feat: Add tabs childs redefinition
adempiere/adempiere-vue pull request #1001
Opened 2021-07-20 03:59 UTC by EdwinBetanc0urt

## Bug report / Feature

#### Screenshot or Gif

https://user-images.githubusercontent.com/20288327/126259860-074b525b-653b-446c-8ea4-9f889aab33d5.mp4

#### Other relevant information
* Your OS: Linux Mint 19.1 Cinnamon x64. 
* Browser: Mozilla Firefox 88.0.1.
* Node.js version: 14.17.0.
* NPM version: 7.19.0.
* adempiere-vue version: 4.3.1.

2021-07-21 04:22 UTC, EdwinBetanc0urt commented
https://user-images.githubusercontent.com/20288327/126430447-698b1209-91a4-46dd-b32c-c97e869180d0.mp4

2021-07-23 02:35 UTC, yamelsenih requested changes

2021-07-23 02:35 UTC, yamelsenih commented on src/views/ADempiere/Window/index.vue
> +
Where is the MultiTab implementation?

2021-07-27 21:57 UTC, yamelsenih commented on src/views/ADempiere/Window/index.vue
> +
?

2021-07-29 23:18 UTC, EdwinBetanc0urt commented on src/views/ADempiere/Window/index.vue
> +
multitab implement

2021-07-30 16:58 UTC, merged