Loading windows with vuex
adempiere/adempiere-vue pull request #1030
Opened 2021-08-09 03:31 UTC by elsiosanchez

#### Screenshot or Gif

![Peek 22-07-2021 09-55](https://user-images.githubusercontent.com/45974454/128657377-a83a71e3-ca57-4811-ab19-81ee106122c6.gif)

#### Other relevant information
- Your OS: Debian 9
- Web Browser: CHrome 
- Node.js version: 18.2.1

2021-08-10 18:54 UTC, EdwinBetanc0urt requested changes

2021-08-10 18:54 UTC, EdwinBetanc0urt commented on src/views/ADempiere/Window/windowUtils.js
> -    tabsList, tabsListParent, tabsListChild,
Keep the list of child tabs, this attribute is mandatory to render child tabs.

2021-08-10 18:54 UTC, EdwinBetanc0urt commented on src/views/ADempiere/Window/windowUtils.js
> -    tabsListChild,
Keep the list of child tabs, this attribute is mandatory to render child tabs.

2021-08-10 18:54 UTC, EdwinBetanc0urt commented on src/views/ADempiere/Window/windowUtils.js
> -  const tabsListChild = tabsList.filter(tabItem => {
this is used to render the child tabs in
https://github.com/adempiere/adempiere-vue/blob/window-redefinition/src/views/ADempiere/Window/StandardWindow.vue#L31

2021-08-12 00:51 UTC, yamelsenih requested changes

2021-08-12 00:51 UTC, yamelsenih commented on src/views/ADempiere/Window/index.vue
> +import { convertWindow } from '@/utils/ADempiere/apiConverts/dictionary.js'
Very old approach. Please keep it as it now

2021-08-12 00:51 UTC, yamelsenih commented on src/store/modules/ADempiere/dictionary/window/actions.js
> +  addWindow({ commit }, windowResponse) {
Already is handle it as mutation

2021-08-20 17:23 UTC, merged