Support to private access feature
adempiere/adempiere-vue pull request #174
Opened 2019-11-22 13:39 UTC by leonel1524

Hello everyone, in this PR, the private access feature on the records is added

2019-11-22 15:21 UTC, yamelsenih commented
Hi @leonel1524 please add a gif for it

2019-11-22 15:35 UTC, leonel1524 commented
> Hi @leonel1524 please add a gif for it

![adempiere-vue-private-access](https://user-images.githubusercontent.com/23490674/69438812-24734180-0d1c-11ea-8a5f-24f5c704d8b9.gif)

2019-11-22 20:58 UTC, yamelsenih commented
Hi @leonel1524 please can you add standard notification for user with "Record Locked" and "Record Unloked"?

Best Regard

2019-11-27 15:59 UTC, leonel1524 commented
> Hi @leonel1524 please can you add standard notification for user with "Record Locked" and "Record Unloked"?
> 
> Best Regard

Hello @yamelsenih, this request has been added
![adempiere-vue-lock-record-notification](https://user-images.githubusercontent.com/23490674/69739008-56661880-110d-11ea-9775-984ebebcb5d3.gif)

2019-11-28 15:09 UTC, yamelsenih requested changes

2019-11-28 15:09 UTC, yamelsenih commented on src/components/ADempiere/ContextMenu/contextMenuMixin.js
> +        this.actions.find(item => item.action === 'unlockRecord').hidden = false
```Javascript
let value = this.actions.find(item => item.action === 'unlockRecord')
value.hidden = false
value.tableName = response.tableName
...
```

2019-11-28 15:09 UTC, yamelsenih commented on src/components/ADempiere/ContextMenu/contextMenuMixin.js
> +        this.actions.find(item => item.action === 'unlockRecord').hidden = false
Test with it

2019-12-02 16:31 UTC, leonel1524 commented on src/components/ADempiere/ContextMenu/contextMenuMixin.js
> +        this.actions.find(item => item.action === 'unlockRecord').hidden = false
solved

2019-12-03 19:18 UTC, merged