Validate collection
adempiere/adempiere-vue pull request #568
Opened 2021-01-14 19:33 UTC by elsiosanchez

- [x] add charge button
- [x] add collection validation 
- [x] correcting the currency converter
- [X] add translation

![collage](https://user-images.githubusercontent.com/45974454/104639049-56acd480-567d-11eb-966e-b80f584f9421.gif)

2021-01-15 05:30 UTC, yamelsenih commented on src/components/ADempiere/Form/VPOS/Collection/index.vue
> +          label = this.$t('form.pos.collect.directDeposit')
Please chage it for value

2021-01-21 22:31 UTC, yamelsenih commented
Please resolve conflicts

2021-01-25 15:40 UTC, yamelsenih requested changes
Remove this

2021-01-25 15:40 UTC, yamelsenih commented on src/utils/ADempiere/apiConverts/core.js
> +      // currencyFrom: convertCurrency(
Remove this

2021-01-25 15:40 UTC, yamelsenih commented on src/store/modules/ADempiere/pointOfSales/collection.js
> +      //   if (element.tenderType === params.tenderType && element.currency.id === params.currency.id) {
Remove this

2021-01-25 15:40 UTC, yamelsenih commented on src/components/ADempiere/Form/VPOS/Collection/fieldsListCollection.js
> +      // handleActionKeyPerformed: true,
Remove this

2021-01-25 15:40 UTC, yamelsenih commented on src/components/ADempiere/Form/VPOS/Collection/fieldsListCollection.js
> +      // handleActionPerformed: true,
Remove this

2021-01-25 15:48 UTC, elsiosanchez commented on src/store/modules/ADempiere/pointOfSales/collection.js
> +      //   if (element.tenderType === params.tenderType && element.currency.id === params.currency.id) {
code snippet removed

2021-01-25 15:49 UTC, elsiosanchez commented on src/components/ADempiere/Form/VPOS/Collection/fieldsListCollection.js
> +      // handleActionKeyPerformed: true,
code snippet removed

2021-01-25 15:49 UTC, elsiosanchez commented on src/components/ADempiere/Form/VPOS/Collection/fieldsListCollection.js
> +      // handleActionPerformed: true,
code snippet removed

2021-01-25 19:06 UTC, merged