Support Binary
adempiere/adempiere-vue pull request #670
Opened 2021-03-15 12:39 UTC by elsiosanchez

## Bug report / Feature
Support to Binary Compunent

#### Steps to reproduce

1. Open a record
2. Upload an image
3. 
#### Screenshot or Gif

![binary](https://user-images.githubusercontent.com/45974454/111154570-bc2c1d00-8569-11eb-81b3-46fca7cb0b05.gif)

#### Link to minimal reproduction

https://demo-ui.erpya.com/#/a48d2596-fb40-11e8-a479-7a0060f0aa01/0/window/113?tabParent=0

#### Other relevant information
- Your OS: Debian 9
- Web Browser: Chrome 
- Node.js version: 10.9.0

#### Issues:
Fixes: #9

2021-03-15 14:36 UTC, yamelsenih requested changes

2021-03-15 14:36 UTC, yamelsenih commented on src/api/ADempiere/field/binary.js
> +  attributesList
What is it?

Please change attributesList by specific attribute

2021-03-17 00:15 UTC, yamelsenih requested changes
Please make this changes for test

2021-03-17 00:15 UTC, yamelsenih commented on src/api/ADempiere/field/binary.js
> +export function requestGetBinary({
Please change this by getResource

2021-03-17 00:15 UTC, yamelsenih commented on src/api/ADempiere/field/binary.js
> +  binary
What is the reason for binary?

2021-03-17 00:15 UTC, yamelsenih commented on src/api/ADempiere/field/binary.js
> +export function requestUpdateBinary({
Please change this for uploadResource

2021-03-17 00:15 UTC, yamelsenih commented on src/api/ADempiere/field/binary.js
> +  attributesList
Is not good when you use generic object, change by real name

2021-03-17 00:15 UTC, yamelsenih commented on src/components/ADempiere/Field/FieldImage.vue
> +      :action="getImage()"
I don't sure if this name is correct

2021-03-17 00:15 UTC, yamelsenih commented on src/components/ADempiere/Field/FieldImage.vue
> +    imageServer() {
??? Please put a correct and descriptive ne

2021-03-17 00:25 UTC, yamelsenih commented
I tasted it and not working for mobile device 
See the gif
![20210316_202453](https://user-images.githubusercontent.com/2333092/111396564-baf80e80-8695-11eb-9788-dedfcbf41f85.gif)

2021-03-17 14:01 UTC, elsiosanchez commented
mobile phone support has been added

#### Screenshot or Gif

![supportmovil](https://user-images.githubusercontent.com/45974454/111479781-aeac9980-8707-11eb-8283-04287daecdf9.gif)

2021-03-21 23:19 UTC, merged