get the currency code to be paid
adempiere/adempiere-vue pull request #750
Opened 2021-04-14 14:05 UTC by elsiosanchez

## Feature
Get the currency code to be paid 
When changing the currency, the current currency code should be displayed
#### Steps to reproduce

1. Create sales order
2. Add a Product
3. Add payments with different currencies
4. When changing the currency, the current currency code should be displayed

#### Screenshot or Gif

![filedCurrency](https://user-images.githubusercontent.com/45974454/114723659-d2fc9580-9d08-11eb-97f5-4d62f6d83745.gif)

#### Link to minimal reproduction

#### Expected behavior
When changing the currency, the current currency code should be displayed

#### Other relevant information
- Your OS: Debian 9
- Web Browser: Chrome
- Node.js version: 10.9

2021-04-14 23:40 UTC, yamelsenih requested changes

2021-04-14 23:40 UTC, yamelsenih commented on src/components/ADempiere/Form/VPOS/Collection/index.vue
> +      return pending / this.convertion
Please use multiply rate instead

2021-04-15 16:17 UTC, oscarinak commented
The pull does not comply with what was communicated and refers to the same observations of pull # 749

2021-04-21 13:20 UTC, oscarinak commented
he pull verification was carried out in the service "https://deploy-preview-750--stoic-lamport-68decf.netlify.app/" where it complies with what is established in the pull, which when changing the currency shows the identification of each one, if it is "Ves" = Bs and its is "USD" = usd
![Verificación_Identificación_Monedas_USD_VES](https://user-images.githubusercontent.com/52334530/115560600-bde0b300-a282-11eb-9601-70eee9e736c9.gif)

2021-04-21 16:15 UTC, merged