record access mode mobile support
adempiere/adempiere-vue pull request #755
Opened 2021-04-16 14:46 UTC by elsiosanchez

## Feature
record access mode mobile support
#### Screenshot or Gif
![Peek 16-04-2021 00-27](https://user-images.githubusercontent.com/45974454/115041867-f5c1b200-9ea0-11eb-8b31-9eae55832c2d.gif)

#### Link to minimal reproduction

#### Other relevant information
- Your OS:Debian9
- Web Browser:Chrome
- Node.js version:10.9

2021-04-17 11:29 UTC, yamelsenih commented
Two comments:
- For desktop the access dialog is not showed
- The **Action** and **References** button is loaded after click evend but the **Relation** button is showed after over event
![Peek 2021-04-17 07-25](https://user-images.githubusercontent.com/2333092/115111481-97eba380-9f4e-11eb-85fc-3cf493a2cf5a.gif)

2021-04-20 20:07 UTC, oscarinak commented
A review of the case was made where it is observed that part of the "Access to Record" option in the ADempiere window its fields adapts to the mobile view, however, as users are added either to "Allow Viewing" or " Hide Registry "the users that are added in the window to check if it is read only or dependent entities these are not displayed as they are loaded or added.

![Error_Acceso_a_Registros](https://user-images.githubusercontent.com/52334530/115457363-6e52a680-a1f2-11eb-84b5-77da0b903fbe.gif)

It is also noted that there is no way to delete the associated users

2021-04-21 16:16 UTC, yamelsenih requested changes
Please add translatioon for this

2021-04-21 16:16 UTC, yamelsenih commented on src/components/ADempiere/RecordAccess/recordAccessMobile.vue
> +        Acceso A registros
Please add translatioon for this

2021-04-21 16:16 UTC, yamelsenih commented on src/components/ADempiere/RecordAccess/recordAccessMobile.vue
> +        Ocultar Registro
Please add translatioon for this

2021-04-21 16:16 UTC, yamelsenih commented on src/components/ADempiere/RecordAccess/recordAccessMobile.vue
> +        Permitir Visualizacion del Registro
Please add translatioon for this

2021-04-21 18:05 UTC, merged