Feature/add column pos
adempiere/adempiere-vue pull request #911
Opened 2021-06-07 15:39 UTC by Andojeda

## Feature
The column amount converted in the point of sale was added

#### Steps to reproduce

1. set the rates of the day
2. open point of sale.
2. select a product from the catalog to add to the order.

#### Screenshot or Gif
![feature-add-column-convertedAmount](https://user-images.githubusercontent.com/85173258/121044369-81f6a400-c783-11eb-9cdf-368371781bdb.gif)

#### Link to minimal reproduction
![feature-add-column-bss-usd](https://user-images.githubusercontent.com/85173258/121044658-9470dd80-c783-11eb-93b4-4dd7ede1b80b.gif)

#### Expected behavior
Automatically show in the column created the conversion of the price of each product as long as the rate of the day is loaded.

2021-06-07 20:14 UTC, EdwinBetanc0urt requested changes

2021-06-07 20:14 UTC, EdwinBetanc0urt commented on src/components/ADempiere/Form/VPOS/Order/orderLineMixin.js
> +          if (!isEmptyValue(response.currencyTo)) {
@Andojeda the `isEmptyValue` function is registered as global so it can be used as `this.isEmptyValue` in component scripts and mixin scripts.

2021-06-07 20:14 UTC, EdwinBetanc0urt commented on src/components/ADempiere/Form/VPOS/Order/orderLineMixin.js
> +import { isEmptyValue } from '@/utils/ADempiere/valueUtils.js'
the `isEmptyValue` function is registered as global and need not be imported into component scripts and mixin scripts. Please remove the import.

2021-06-07 21:21 UTC, Andojeda commented on src/components/ADempiere/Form/VPOS/Order/orderLineMixin.js
> +import { isEmptyValue } from '@/utils/ADempiere/valueUtils.js'
It was already corrected

2021-06-10 14:10 UTC, oscarinak commented
The PR was verified where it is observed that it complies with what is described in the PR, it performs the conversion of the amounts by products at the rate of the day, whether it is working with the USD or VES point of sale

![Uploading Verificación_PullR_911.gif…]()

2021-06-10 14:10 UTC, oscarinak commented
Good

2021-06-10 20:23 UTC, yamelsenih requested changes

2021-06-10 20:23 UTC, yamelsenih commented on src/components/ADempiere/Form/VPOS/Order/orderLineMixin.js
> +    formatDate2(date) {
What is it? already exist a util class for format date and the name must be more explicit

2021-06-10 20:23 UTC, yamelsenih commented on src/components/ADempiere/Form/VPOS/Order/orderLineMixin.js
> +    totalAmountConverted(value) {
Change by covertedAmountAsTotal

2021-06-10 20:23 UTC, yamelsenih commented on src/components/ADempiere/Form/VPOS/Order/orderLineMixin.js
> +        conversionDate: this.formatDate2(new Date()),
it is unnecessary

2021-06-10 21:22 UTC, Andojeda reviewed
observations were corrected

2021-06-11 21:13 UTC, merged