Bugreport918 vertical spacing in side menu
adempiere/adempiere-vue pull request #926
Opened 2021-06-16 02:09 UTC by sofia-ester-calderon

Corrected the big vertical spacing in the side menu (issue only present in Firefox).

## Bug report / Feature

Closes #918 

#### Screenshot or Gif

**Firefox:**
<img width="1220" alt="Screen Shot 2021-06-16 at 12 07 29 pm" src="https://user-images.githubusercontent.com/54033498/122147028-7732c200-ce9b-11eb-8718-467f9e426557.png">

**Chrome:**
<img width="969" alt="Screen Shot 2021-06-16 at 12 08 04 pm" src="https://user-images.githubusercontent.com/54033498/122147085-8d408280-ce9b-11eb-8a05-dd204857e361.png">

2021-06-17 05:16 UTC, sofia-ester-calderon commented
also fixed the styling of sidbar when menu is collapsed

**Before:**
<img width="404" alt="Screen Shot 2021-06-17 at 3 15 00 pm" src="https://user-images.githubusercontent.com/54033498/122335551-cf8ec000-cf7e-11eb-89cb-5ee2a9676748.png">

**After:**

- Firefox:
<img width="577" alt="Screen Shot 2021-06-17 at 3 10 28 pm" src="https://user-images.githubusercontent.com/54033498/122335597-e46b5380-cf7e-11eb-8e8d-6614d5307e77.png">

- Chrome:
<img width="904" alt="Screen Shot 2021-06-17 at 3 10 00 pm" src="https://user-images.githubusercontent.com/54033498/122335631-ee8d5200-cf7e-11eb-8e5c-c713b72445ab.png">

- Mobile:
<img width="447" alt="Screen Shot 2021-06-17 at 3 11 28 pm" src="https://user-images.githubusercontent.com/54033498/122335664-f947e700-cf7e-11eb-9988-378af9f68b8f.png">

2021-06-17 08:11 UTC, sofia-ester-calderon commented
Also fixed the style of collapsed sidebar menu.

**Before**
<img width="404" alt="Screen Shot 2021-06-17 at 3 15 00 pm" src="https://user-images.githubusercontent.com/54033498/122357669-48017b00-cf97-11eb-9a36-a698058eefd2.png">


**After**

- Firefox
<img width="557" alt="Screen Shot 2021-06-17 at 6 08 03 pm" src="https://user-images.githubusercontent.com/54033498/122357730-53ed3d00-cf97-11eb-88ec-e19ae3317a95.png">

- Chrome
<img width="499" alt="Screen Shot 2021-06-17 at 6 08 25 pm" src="https://user-images.githubusercontent.com/54033498/122357752-5a7bb480-cf97-11eb-83dd-943c1dc8ba7b.png">

- Mobile
<img width="408" alt="Screen Shot 2021-06-17 at 6 11 09 pm" src="https://user-images.githubusercontent.com/54033498/122357837-6cf5ee00-cf97-11eb-9260-56db1e038ee9.png">

2021-06-17 12:36 UTC, EdwinBetanc0urt requested changes

2021-06-17 12:36 UTC, EdwinBetanc0urt commented on src/layout/components/Sidebar/Item.vue
> +    padding: 18px 23px 18px 0;
Please delete the spaces at the end of the line as it gives a warning message with the eslint

![compile-with-error](https://user-images.githubusercontent.com/20288327/122397171-b5d18680-cf46-11eb-8144-6e3cd2ed0dd4.png)

2021-06-18 01:17 UTC, EdwinBetanc0urt commented
Hi @sofia-ester-calderon, I ran the tests and they were successful on both firefox desktop for linux and firefox mobile for android.

Mozilla Firefox desktop:
https://user-images.githubusercontent.com/20288327/122490786-c0c10100-cfb0-11eb-86e3-ebc39b68726f.mp4


Mozilla Firefox mobile:

https://user-images.githubusercontent.com/20288327/122490841-dfbf9300-cfb0-11eb-8abd-c0ba2647392e.mp4


@yamelsenih  please merge this pull request.

2021-06-18 04:06 UTC, EdwinBetanc0urt approved these changes

2021-06-18 19:51 UTC, yamelsenih commented
Hi @sofia-ester-calderon already exist some changes by @elsiosanchez for SidebarItem, can you review and resolve conflicts?

Best regards

2021-06-18 23:01 UTC, sofia-ester-calderon commented
> Hi @sofia-ester-calderon already exist some changes by @elsiosanchez for SidebarItem, can you review and resolve conflicts?
> 
> Best regards

Done! Happy weekend :)

2021-06-18 23:03 UTC, yamelsenih commented
Great!!! Thanks... Me too

2021-06-18 23:04 UTC, merged