Add Form Allocation of Payments
adempiere/adempiere-vue pull request #933
Opened 2021-06-22 02:28 UTC by elsiosanchez

## Feature
Proposal for the payment assignment form

#### Screenshot or Gif
Behavior when there is a difference between payment and invoice
![success](https://user-images.githubusercontent.com/45974454/122853163-cc2d6880-d2df-11eb-80f1-b17ea2e47a56.gif)

![error](https://user-images.githubusercontent.com/45974454/122853180-d0f21c80-d2df-11eb-97bd-be153964e994.gif)

#### Other relevant information
- Your OS: Debian 9
- Web Browser: Chrome
- Node.js version: 18.0

2021-06-23 21:03 UTC, yamelsenih requested changes

2021-06-23 21:03 UTC, yamelsenih commented on config/default.json
> +  "allocationPayments": {
change by "paymentAllocation"

2021-06-23 21:03 UTC, yamelsenih commented on src/api/ADempiere/form/v-allocation.js
> +// ADempiere-Vue (Frontend) for ADempiere ERP & CRM Smart Business Solution
Change name by paymentAllocation

2021-06-23 21:03 UTC, yamelsenih commented on src/components/ADempiere/Form/allocationPayments/Invoices/index.vue
> + ADempiere-Vue (Frontend) for ADempiere ERP & CRM Smart Business Solution
Change folder by paymentAllocation

2021-08-22 03:38 UTC, EdwinBetanc0urt requested changes

2021-08-22 03:38 UTC, EdwinBetanc0urt commented on src/components/ADempiere/Form/allocationPayments/Summary/index.vue
> +    console.log('alo')
@elsiosanchez remove this created

2021-08-22 03:38 UTC, EdwinBetanc0urt commented on src/components/ADempiere/Form/paymentAllocation/tableFrom.vue
> +    getSummaries(param) {
Duplicate method, please add support in another utility file, should be called `numberFormat`, to centralize and import it in your implementations.

2022-02-02 13:14 UTC, closed without merging